server:
  port: 8080

spring:
  application:
    name: cvc-Hotelaria
  jackson:
      default-property-inclusion: NON_NULL
  sleuth:
    sampler:
      probability: 1.0

urlBrokerAvail: https://cvcbackendhotel.herokuapp.com/hotels/avail/ # 

urlBrokerHotels: https://cvcbackendhotel.herokuapp.com/hotels/ # 